# Generated by Django 4.1.3 on 2022-11-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedOnDate', models.DateTimeField(auto_now=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('CreateByUserId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdProjects', to='kt_auth.users')),
                ('UpdatedByUserId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedProjects', to='kt_auth.users')),
            ],
        ),
    ]
