# Generated by Django 4.1.3 on 2022-11-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
        ('kt_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='CreateByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdProjects', to='kt_auth.users'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='UpdatedByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedProjects', to='kt_auth.users'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
