# Generated by Django 4.1.3 on 2022-12-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporteddataset',
            name='created_by_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kt_auth.users'),
        ),
    ]
