# Generated by Django 4.1.3 on 2022-11-29 17:29

import annotation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kt_tasks', '0004_alter_tasks_mainimagefile_and_more'),
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of dictionary ex. indian_person_names_english_cnt_1000', max_length=255, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('image', 'image')], help_text='type of content 1) text -- means words or lines text 2) image: path of images', max_length=5)),
                ('file', models.FileField(upload_to='dict/')),
                ('desc', models.TextField(blank=True, help_text='Description of Dictionary', null=True)),
                ('desc_html', models.TextField(blank=True, help_text='Description of Dictionary in html format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdByUser', to='kt_auth.users')),
                ('updated_by_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedByUser', to='kt_auth.users')),
            ],
        ),
        migrations.CreateModel(
            name='FontHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of font ex. Times new roman, Helvetica etc..', max_length=255, null=True)),
                ('file', models.FileField(upload_to='fonts/')),
                ('desc', models.TextField(blank=True, help_text='Description of Font', null=True)),
                ('desc_html', models.TextField(blank=True, help_text='Description of Font in html format', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of language ex. English, Arabic etc', max_length=50, null=True)),
                ('short_name', models.CharField(blank=True, help_text='short name of language ex. en for English and mar for Marathi', max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordAnnotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.IntegerField(blank=True, help_text='Word index in image', null=True)),
                ('text', models.CharField(blank=True, help_text='recognized text', max_length=255, null=True)),
                ('box_coordinates', models.TextField(blank=True, help_text='Bounding box coordinates. TODO. use ArrayField or JSONfield later', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.fonthub')),
                ('lang', models.ForeignKey(blank=True, help_text='Language of word', on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.languagehub')),
                ('task', models.ForeignKey(blank=True, help_text='Task id in which this line annotation belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='kt_tasks.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='LineAnnotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.IntegerField(blank=True, help_text='Line index in image', null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('image', 'image')], help_text='type of bounding box -- what bounding box holding 1) text 2) image', max_length=5)),
                ('text', models.CharField(blank=True, help_text='text if content type is `text`', max_length=255, null=True)),
                ('is_fixed_text', models.BooleanField(default=False)),
                ('is_render_text', models.BooleanField(default=True)),
                ('box_coordinates', models.TextField(blank=True, help_text='Bounding box coordinates. TODO. use ArrayField or JSONfield later', null=True)),
                ('key_label', models.CharField(blank=True, default='OTHER', help_text='Key name for structured data training purpose ex. PERSON_NAME, BIRTH_DATE etc..', max_length=255, null=True)),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to=annotation.models.cropped_line_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dict', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.dictionaryhub')),
                ('task', models.ForeignKey(blank=True, help_text='Task id in which this line annotation belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='kt_tasks.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='fonthub',
            name='lang',
            field=models.ForeignKey(blank=True, help_text='Language in which this font file belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.languagehub'),
        ),
    ]
