# Generated by Django 4.1.3 on 2022-11-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
        ('annotation', '0002_lineannotation_rename_wordannotations_wordannotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryhub',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdByUser', to='kt_auth.users'),
        ),
        migrations.AlterField(
            model_name='dictionaryhub',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedByUser', to='kt_auth.users'),
        ),
    ]
