# Generated by Django 4.1.3 on 2022-11-30 16:17

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_alter_dictionaryhub_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonthub',
            name='file',
            field=models.FileField(upload_to=annotation.models.font_file_path),
        ),
    ]
