# Generated by Django 4.1.3 on 2022-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_wordannotation_font_color_wordannotation_heigh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerenderingparts',
            name='font_size',
            field=models.IntegerField(blank=True, default=32, help_text='Font size for generated text', null=True),
        ),
    ]
