# Generated by Django 4.1.3 on 2022-12-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_alter_linerenderingparts_font_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineRenderingParts',
            new_name='LineRenderingPart',
        ),
    ]
