# Generated by Django 4.1.3 on 2022-12-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_tasks', '0008_remove_tasks_is_line_annotation_done_and_more'),
        ('annotation', '0007_rename_linerenderingparts_linerenderingpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_data', models.CharField(blank=True, help_text='set data', max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, help_text='count', null=True)),
                ('description', models.TextField(blank=True, help_text='description', null=True)),
                ('select_task', models.ForeignKey(blank=True, help_text='select task', on_delete=django.db.models.deletion.DO_NOTHING, to='kt_tasks.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='GenratePanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_data', models.CharField(blank=True, help_text='set data', max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, help_text='count', null=True)),
                ('description', models.TextField(blank=True, help_text='description', null=True)),
                ('select_task', models.ForeignKey(blank=True, help_text='select task', on_delete=django.db.models.deletion.DO_NOTHING, to='kt_tasks.tasks')),
            ],
        ),
    ]
