# Generated by Django 4.1.3 on 2022-12-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_volumecomment_genratepandata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumecomment',
            name='select_task',
        ),
        migrations.DeleteModel(
            name='GenratePanData',
        ),
        migrations.DeleteModel(
            name='VolumeComment',
        ),
    ]
