# Generated by Django 4.1.3 on 2022-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_volumecomment_genratepandata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordannotation',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordannotation',
            name='is_italic',
            field=models.BooleanField(default=True),
        ),
    ]
