# Generated by Django 4.1.3 on 2022-12-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_remove_volumecomment_select_task_and_more'),
        ('annotation', '0009_wordannotation_is_bold_wordannotation_is_italic'),
    ]

    operations = [
    ]
