# Generated by Django 4.1.3 on 2022-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_merge_20221204_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmetainfo',
            name='grouped_word_annotation',
            field=models.ManyToManyField(blank=True, help_text='source dataset that has been used to export this data. It amy be one or more', related_name='grouped_words_annotation_by_line', to='annotation.wordannotation'),
        ),
    ]
