# Generated by Django 4.1.3 on 2022-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_alter_annotationmetainfo_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerendering',
            name='font_color',
            field=models.CharField(blank=True, help_text='font color', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linerendering',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='top position of annotation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='linerendering',
            name='left',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='left position of annotation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='linerendering',
            name='top',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='top position of annotation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='linerendering',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='top position of annotation', max_digits=5, null=True),
        ),
    ]
