# Generated by Django 4.1.3 on 2022-12-06 05:11

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_alter_annotationmetainfo_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmetainfo',
            name='image_visualized_lines',
            field=models.ImageField(blank=True, help_text='image with line level coordinates visualization', null=True, upload_to=annotation.models.annotation_meta_info_path),
        ),
        migrations.AddField(
            model_name='annotationmetainfo',
            name='image_visualized_words',
            field=models.ImageField(blank=True, help_text='image with word level coordinates visualization', null=True, upload_to=annotation.models.annotation_meta_info_path),
        ),
    ]
