# Generated by Django 4.1.3 on 2022-12-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_annotationmetainfo_image_visualized_lines_and_more'),
        ('annotation', '0016_linerendering_font_color_linerendering_height_and_more'),
    ]

    operations = [
    ]
