# Generated by Django 4.1.3 on 2022-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0017_merge_20221206_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineannotationextrainfo',
            name='grouped_words_annotation_by_line',
        ),
        migrations.AddField(
            model_name='annotationmetainfo',
            name='is_words_grouped_by_line',
            field=models.BooleanField(blank=True, default=False, help_text='After grouping words by line annotation, it will be turned on', null=True),
        ),
        migrations.AddField(
            model_name='lineannotationextrainfo',
            name='inside_words',
            field=models.CharField(blank=True, help_text='words ids that are inside line as per coordinate center -- or -- Word annotation ids that are been grouped together as per line coordinates', max_length=255, null=True),
        ),
    ]
