# Generated by Django 4.1.3 on 2022-12-06 13:56

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_remove_lineannotationextrainfo_grouped_words_annotation_by_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmetainfo',
            name='image_grouped_words',
            field=models.ImageField(blank=True, help_text='Visualization of word groups', null=True, upload_to=annotation.models.annotation_meta_info_path),
        ),
    ]
