# Generated by Django 4.1.3 on 2022-12-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0019_annotationmetainfo_image_grouped_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationmetainfo',
            old_name='image_grouped_words',
            new_name='image_visualized_grouped_words',
        ),
    ]
