# Generated by Django 4.1.3 on 2022-11-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kt_auth', '0001_initial'),
        ('kt_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(blank=True, max_length=255, null=True)),
                ('MainImageFile', models.TextField(blank=True, null=True)),
                ('TextRemovedImageFile', models.TextField(blank=True, null=True)),
                ('WordAnnotationList', models.TextField(blank=True, null=True)),
                ('CreatedOnDate', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('CreateByUserId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdTasks', to='kt_auth.users')),
                ('ProjectId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='kt_projects.projects')),
                ('UpdatedByUserId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedTasks', to='kt_auth.users')),
            ],
        ),
    ]
