# Generated by Django 4.1.3 on 2022-11-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='MainImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='TextRemovedImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
