# Generated by Django 4.1.3 on 2022-11-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
        ('kt_tasks', '0004_alter_tasks_mainimagefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='CreateByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdTasks', to='kt_auth.users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='UpdatedByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedTasks', to='kt_auth.users'),
        ),
    ]
