# Generated by Django 4.1.3 on 2022-11-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_tasks', '0005_alter_tasks_createbyuserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='meta_json_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
