# Generated by Django 4.1.3 on 2022-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_tasks', '0006_tasks_meta_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='WordAnnotationList',
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_line_annotation_done',
            field=models.BooleanField(blank=True, default=False, help_text='Once user perform line level annotations and press save button line annotations will be saved and this will turned to true', null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_word_annotation_done',
            field=models.BooleanField(blank=True, default=False, help_text='After word level annotation save this will be turned on', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='meta_json_file',
            field=models.FileField(blank=True, help_text='Meta data file to render new id card', null=True, upload_to='images/'),
        ),
    ]
