# Generated by Django 4.1.3 on 2022-12-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kt_tasks', '0007_remove_tasks_wordannotationlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_line_annotation_done',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='is_word_annotation_done',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='meta_json_file',
        ),
    ]
