# Generated by Django 4.1.3 on 2022-12-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kt_projects', '0003_alter_projects_createbyuserid_and_more'),
        ('kt_auth', '0002_alter_users_role_delete_userroles'),
        ('kt_tasks', '0008_remove_tasks_is_line_annotation_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='CreateByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdTasks', to='kt_auth.users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ProjectId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kt_projects.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='UpdatedByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedTasks', to='kt_auth.users'),
        ),
    ]
