# Generated by Django 4.1.3 on 2022-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Role',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
